### ISSUE TITLE
Error: The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by ksprehe** [cjyoung/MouseBitesWPF#12]
Looks like authentication model may have changed.  Receiving a 401 when trying to get the list of restaurants.  If you are still monitoring/maintaining the code let me know if you have any quick ideas or I will spend some time this week seeing if there are options around this.

**Comment by cjyoung** [comment]
Thanks for reporting the issue. It looks like I had some authentication logic in an older search function that I was able to leverage to get this working again. When you have a chance, can you pull the latest code and see if it works for you now? Thanks!

**Comment by ksprehe** [comment]
Working great, thanks!
