### ISSUE TITLE
Dining Event Doesn't Work?

### ISSUE THREAD

**Issue by otictac1** [cjyoung/MouseBitesWPF#14]
Hello sir,

  I noticed that dining events (such as https://disneyworld.disney.go.com/dining/hollywood-studios/fantasmic-dining-package/).  I've attempted to make some changes to the posting string and it has an unexpected result.  It returns that there is no availability at a given restaurant, at a given time, or a given day, but, oddly, I know that there is at least one availability.  

Did you have any luck getting dining events to work?  Here is what my post string looks like now:

`string postString = string.Format( "&searchDate={1}" + "&restaurants={5}" +
                                                "&skipPricing=true" +
                                                "&searchTime={2}" +
                                                "&partySize={3}" + "&diningProduct=Dining-Event" +
                                                "&id={0}%3BentityType%3DDining-Event" +
                                                "&type=dining" +
                                                "&pep_csrf={4}",
                                                   criteria[3],
                                                    criteria[0],
                                                    criteria[1],
                                                    criteria[2],
                                                    pep_csrf, criteria[8]); `

Just wondering if you had any thoughts on why that would return a result, but just the wrong one?

**Comment by otictac1** [comment]
You know what?  I'm really dumb.  I was reading in from a CSV and I had a space in front of the number 2 in partySize.  I fixed that and I'm good now.  Sorry for bothering you.

**Comment by cjyoung** [comment]
No worries. Glad you were able to figure it out. Sorry for the slow reply - I was out of town for a little bit. If you run into any other issues, let me know and I'll see what I can do to help
